### ISSUE TITLE
I see scores of copilot responses on LiteralAI dashboard. But the token used are are not updated. Always shows 0.

### ISSUE THREAD

**Issue by kumar781** [Chainlit/literalai-docs#115]
### LiteralAI "tokens used" not getting updated
I have a copilot built with langchain and AzureOpenAI LLMs. I am using chainlit for the UI. I have set the LiteralAI key as env variable and am able to see feedback scores to copilot responses on LiteralAI dashboard. But the tokens used still shows 0. It doesn't get updated. 
![Screenshot 2024-09-11 163923](https://github.com/user-attachments/assets/baee5556-b0e9-4f9d-8869-46ba0012343c)

**Comment by constantinidan** [comment]
@kumar781 what integration are you using?

**Comment by kumar781** [comment]
I am using gpt 4 turbo

**Comment by kumar781** [comment]
@constantinidan  can you elaborate your previous question, I couldn't completely follow.

**Comment by desaxce** [comment]
@kumar781 Just merged the change, will release a newer version end of day today.

**Comment by kumar781** [comment]
Thanks @desaxce. Please do let me know when the release is available.

**Comment by kumar781** [comment]
Will it work with AzureOpenai GPT 4 turbo?

**Comment by kumar781** [comment]
can you suggest which libraries should i upgrade & to which version, to get the fixes you mentioned?
