### ISSUE TITLE
In Chainlit, I put LITERAL_API_KEY, but LiteralAI can't receive any data from my Chainlit web page.

### ISSUE THREAD

**Issue by kungmo** [Chainlit/literalai-docs#92]
Path: /integrations/chainlit

Hello.
In the page 'https://docs.getliteral.ai/integrations/chainlit', it says "just set the LITERAL_API_KEY environment variable to your API key and run your application as you normally would."

So in my Chainlit web page, I put only this code.

os.environ["LITERAL_API_KEY"] = "lsk_tg..... (my API key)"

But, LiteralAI can't receive any data from my Chainlit web page.

What is wrong with my python file? 

Thank you.

**Comment by willydouhard** [comment]
What version of Chainlit are you using. Also can you try adding the environment variable in your `.env` file? Chainlit loads it automatically.

**Comment by desaxce** [comment]
Closing stale issue, lacking needed info to investigate.
